namespace QuanLyDVGiaoHang.GUI.ThongTinTaiKhoan
{
    partial class FrmThongTinTK
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmThongTinTK));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.panel1 = new System.Windows.Forms.Panel();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.txtSoDT = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtHoTen = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTenCuaHang = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pnTTTaiKhoan = new System.Windows.Forms.Panel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.txtMatKhauCu = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCapNhatMatKhau = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtNhapLaiMatKhau = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.txtMatKhauMoi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.txtDiaChi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cbXa = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cbHuyen = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cbTinh = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.pnTTTaiKhoan.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.Navy;
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(670, 41);
            this.panel1.TabIndex = 0;
            // 
            // groupBox2
            // 
            this.groupBox2.Location = new System.Drawing.Point(0, 60);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(238, 10);
            this.groupBox2.TabIndex = 6;
            this.groupBox2.TabStop = false;
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox1.Location = new System.Drawing.Point(446, 60);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(224, 10);
            this.groupBox1.TabIndex = 5;
            this.groupBox1.TabStop = false;
            // 
            // label1
            // 
            this.label1.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.Navy;
            this.label1.Location = new System.Drawing.Point(235, 44);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(217, 30);
            this.label1.TabIndex = 4;
            this.label1.Text = "Thông Tin Tài Khoản";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(14, 140);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(52, 20);
            this.label5.TabIndex = 15;
            this.label5.Text = "Số ĐT:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(14, 84);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(79, 20);
            this.label2.TabIndex = 13;
            this.label2.Text = "Họ Và Tên:";
            // 
            // txtSoDT
            // 
            this.txtSoDT.AcceptsReturn = false;
            this.txtSoDT.AcceptsTab = false;
            this.txtSoDT.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtSoDT.AnimationSpeed = 200;
            this.txtSoDT.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSoDT.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSoDT.BackColor = System.Drawing.Color.Transparent;
            this.txtSoDT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSoDT.BackgroundImage")));
            this.txtSoDT.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSoDT.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSoDT.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSoDT.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSoDT.BorderRadius = 1;
            this.txtSoDT.BorderThickness = 1;
            this.txtSoDT.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSoDT.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoDT.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSoDT.DefaultText = "";
            this.txtSoDT.FillColor = System.Drawing.Color.White;
            this.txtSoDT.HideSelection = true;
            this.txtSoDT.IconLeft = null;
            this.txtSoDT.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoDT.IconPadding = 10;
            this.txtSoDT.IconRight = null;
            this.txtSoDT.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoDT.Lines = new string[0];
            this.txtSoDT.Location = new System.Drawing.Point(17, 163);
            this.txtSoDT.MaxLength = 32767;
            this.txtSoDT.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSoDT.Modified = false;
            this.txtSoDT.Multiline = false;
            this.txtSoDT.Name = "txtSoDT";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoDT.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSoDT.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoDT.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoDT.OnIdleState = stateProperties4;
            this.txtSoDT.Padding = new System.Windows.Forms.Padding(3);
            this.txtSoDT.PasswordChar = '\0';
            this.txtSoDT.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSoDT.PlaceholderText = "Nhập Số ĐT";
            this.txtSoDT.ReadOnly = false;
            this.txtSoDT.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSoDT.SelectedText = "";
            this.txtSoDT.SelectionLength = 0;
            this.txtSoDT.SelectionStart = 0;
            this.txtSoDT.ShortcutsEnabled = true;
            this.txtSoDT.Size = new System.Drawing.Size(303, 30);
            this.txtSoDT.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSoDT.TabIndex = 18;
            this.txtSoDT.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSoDT.TextMarginBottom = 0;
            this.txtSoDT.TextMarginLeft = 3;
            this.txtSoDT.TextMarginTop = 0;
            this.txtSoDT.TextPlaceholder = "Nhập Số ĐT";
            this.txtSoDT.UseSystemPasswordChar = false;
            this.txtSoDT.WordWrap = true;
            // 
            // txtHoTen
            // 
            this.txtHoTen.AcceptsReturn = false;
            this.txtHoTen.AcceptsTab = false;
            this.txtHoTen.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtHoTen.AnimationSpeed = 200;
            this.txtHoTen.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtHoTen.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtHoTen.BackColor = System.Drawing.Color.Transparent;
            this.txtHoTen.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtHoTen.BackgroundImage")));
            this.txtHoTen.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtHoTen.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtHoTen.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtHoTen.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtHoTen.BorderRadius = 1;
            this.txtHoTen.BorderThickness = 1;
            this.txtHoTen.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtHoTen.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtHoTen.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtHoTen.DefaultText = "";
            this.txtHoTen.FillColor = System.Drawing.Color.White;
            this.txtHoTen.HideSelection = true;
            this.txtHoTen.IconLeft = null;
            this.txtHoTen.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtHoTen.IconPadding = 10;
            this.txtHoTen.IconRight = null;
            this.txtHoTen.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtHoTen.Lines = new string[0];
            this.txtHoTen.Location = new System.Drawing.Point(18, 107);
            this.txtHoTen.MaxLength = 32767;
            this.txtHoTen.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtHoTen.Modified = false;
            this.txtHoTen.Multiline = false;
            this.txtHoTen.Name = "txtHoTen";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtHoTen.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtHoTen.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtHoTen.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtHoTen.OnIdleState = stateProperties8;
            this.txtHoTen.Padding = new System.Windows.Forms.Padding(3);
            this.txtHoTen.PasswordChar = '\0';
            this.txtHoTen.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtHoTen.PlaceholderText = "Nhập Họ Tên";
            this.txtHoTen.ReadOnly = false;
            this.txtHoTen.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtHoTen.SelectedText = "";
            this.txtHoTen.SelectionLength = 0;
            this.txtHoTen.SelectionStart = 0;
            this.txtHoTen.ShortcutsEnabled = true;
            this.txtHoTen.Size = new System.Drawing.Size(303, 30);
            this.txtHoTen.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtHoTen.TabIndex = 16;
            this.txtHoTen.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtHoTen.TextMarginBottom = 0;
            this.txtHoTen.TextMarginLeft = 3;
            this.txtHoTen.TextMarginTop = 0;
            this.txtHoTen.TextPlaceholder = "Nhập Họ Tên";
            this.txtHoTen.UseSystemPasswordChar = false;
            this.txtHoTen.WordWrap = true;
            // 
            // txtTenCuaHang
            // 
            this.txtTenCuaHang.AcceptsReturn = false;
            this.txtTenCuaHang.AcceptsTab = false;
            this.txtTenCuaHang.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtTenCuaHang.AnimationSpeed = 200;
            this.txtTenCuaHang.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTenCuaHang.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTenCuaHang.BackColor = System.Drawing.Color.Transparent;
            this.txtTenCuaHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTenCuaHang.BackgroundImage")));
            this.txtTenCuaHang.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTenCuaHang.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTenCuaHang.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTenCuaHang.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTenCuaHang.BorderRadius = 1;
            this.txtTenCuaHang.BorderThickness = 1;
            this.txtTenCuaHang.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTenCuaHang.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenCuaHang.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTenCuaHang.DefaultText = "";
            this.txtTenCuaHang.FillColor = System.Drawing.Color.White;
            this.txtTenCuaHang.HideSelection = true;
            this.txtTenCuaHang.IconLeft = null;
            this.txtTenCuaHang.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenCuaHang.IconPadding = 10;
            this.txtTenCuaHang.IconRight = null;
            this.txtTenCuaHang.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenCuaHang.Lines = new string[0];
            this.txtTenCuaHang.Location = new System.Drawing.Point(18, 219);
            this.txtTenCuaHang.MaxLength = 32767;
            this.txtTenCuaHang.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTenCuaHang.Modified = false;
            this.txtTenCuaHang.Multiline = false;
            this.txtTenCuaHang.Name = "txtTenCuaHang";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenCuaHang.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTenCuaHang.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenCuaHang.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenCuaHang.OnIdleState = stateProperties12;
            this.txtTenCuaHang.Padding = new System.Windows.Forms.Padding(3);
            this.txtTenCuaHang.PasswordChar = '\0';
            this.txtTenCuaHang.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTenCuaHang.PlaceholderText = "Nhập Tên Cửa Hàng";
            this.txtTenCuaHang.ReadOnly = false;
            this.txtTenCuaHang.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTenCuaHang.SelectedText = "";
            this.txtTenCuaHang.SelectionLength = 0;
            this.txtTenCuaHang.SelectionStart = 0;
            this.txtTenCuaHang.ShortcutsEnabled = true;
            this.txtTenCuaHang.Size = new System.Drawing.Size(303, 30);
            this.txtTenCuaHang.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTenCuaHang.TabIndex = 30;
            this.txtTenCuaHang.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTenCuaHang.TextMarginBottom = 0;
            this.txtTenCuaHang.TextMarginLeft = 3;
            this.txtTenCuaHang.TextMarginTop = 0;
            this.txtTenCuaHang.TextPlaceholder = "Nhập Tên Cửa Hàng";
            this.txtTenCuaHang.UseSystemPasswordChar = false;
            this.txtTenCuaHang.WordWrap = true;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(14, 196);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(105, 20);
            this.label6.TabIndex = 29;
            this.label6.Text = "Tên Cửa Hàng:";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(14, 251);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(49, 20);
            this.label4.TabIndex = 27;
            this.label4.Text = "Email:";
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.BackColor = System.Drawing.Color.Transparent;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEmail.BorderRadius = 1;
            this.txtEmail.BorderThickness = 1;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.White;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(18, 274);
            this.txtEmail.MaxLength = 32767;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties16;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "Nhập Email";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(303, 30);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmail.TabIndex = 28;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 3;
            this.txtEmail.TextMarginTop = 0;
            this.txtEmail.TextPlaceholder = "Nhập Email";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // pnTTTaiKhoan
            // 
            this.pnTTTaiKhoan.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.pnTTTaiKhoan.Controls.Add(this.pictureBox1);
            this.pnTTTaiKhoan.Controls.Add(this.txtMatKhauCu);
            this.pnTTTaiKhoan.Controls.Add(this.label8);
            this.pnTTTaiKhoan.Controls.Add(this.bunifuButton3);
            this.pnTTTaiKhoan.Controls.Add(this.bunifuButton2);
            this.pnTTTaiKhoan.Controls.Add(this.btnCapNhatMatKhau);
            this.pnTTTaiKhoan.Controls.Add(this.txtNhapLaiMatKhau);
            this.pnTTTaiKhoan.Controls.Add(this.label7);
            this.pnTTTaiKhoan.Controls.Add(this.txtMatKhauMoi);
            this.pnTTTaiKhoan.Controls.Add(this.label3);
            this.pnTTTaiKhoan.Location = new System.Drawing.Point(339, 85);
            this.pnTTTaiKhoan.Name = "pnTTTaiKhoan";
            this.pnTTTaiKhoan.Size = new System.Drawing.Size(316, 396);
            this.pnTTTaiKhoan.TabIndex = 32;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::QuanLyDVGiaoHang.Properties.Resources.icons8_user_94;
            this.pictureBox1.Location = new System.Drawing.Point(7, 3);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(303, 96);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 47;
            this.pictureBox1.TabStop = false;
            // 
            // txtMatKhauCu
            // 
            this.txtMatKhauCu.AcceptsReturn = false;
            this.txtMatKhauCu.AcceptsTab = false;
            this.txtMatKhauCu.AnimationSpeed = 200;
            this.txtMatKhauCu.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMatKhauCu.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMatKhauCu.BackColor = System.Drawing.Color.Transparent;
            this.txtMatKhauCu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMatKhauCu.BackgroundImage")));
            this.txtMatKhauCu.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMatKhauCu.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMatKhauCu.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMatKhauCu.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMatKhauCu.BorderRadius = 1;
            this.txtMatKhauCu.BorderThickness = 1;
            this.txtMatKhauCu.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMatKhauCu.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatKhauCu.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtMatKhauCu.DefaultText = "";
            this.txtMatKhauCu.FillColor = System.Drawing.Color.White;
            this.txtMatKhauCu.HideSelection = true;
            this.txtMatKhauCu.IconLeft = null;
            this.txtMatKhauCu.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatKhauCu.IconPadding = 10;
            this.txtMatKhauCu.IconRight = null;
            this.txtMatKhauCu.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatKhauCu.Lines = new string[0];
            this.txtMatKhauCu.Location = new System.Drawing.Point(7, 125);
            this.txtMatKhauCu.MaxLength = 32767;
            this.txtMatKhauCu.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMatKhauCu.Modified = false;
            this.txtMatKhauCu.Multiline = false;
            this.txtMatKhauCu.Name = "txtMatKhauCu";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatKhauCu.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMatKhauCu.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatKhauCu.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatKhauCu.OnIdleState = stateProperties20;
            this.txtMatKhauCu.Padding = new System.Windows.Forms.Padding(3);
            this.txtMatKhauCu.PasswordChar = '\0';
            this.txtMatKhauCu.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMatKhauCu.PlaceholderText = "Nhập Mật Khẩu Cũ";
            this.txtMatKhauCu.ReadOnly = false;
            this.txtMatKhauCu.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMatKhauCu.SelectedText = "";
            this.txtMatKhauCu.SelectionLength = 0;
            this.txtMatKhauCu.SelectionStart = 0;
            this.txtMatKhauCu.ShortcutsEnabled = true;
            this.txtMatKhauCu.Size = new System.Drawing.Size(303, 30);
            this.txtMatKhauCu.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMatKhauCu.TabIndex = 46;
            this.txtMatKhauCu.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMatKhauCu.TextMarginBottom = 0;
            this.txtMatKhauCu.TextMarginLeft = 3;
            this.txtMatKhauCu.TextMarginTop = 0;
            this.txtMatKhauCu.TextPlaceholder = "Nhập Mật Khẩu Cũ";
            this.txtMatKhauCu.UseSystemPasswordChar = false;
            this.txtMatKhauCu.WordWrap = true;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(3, 102);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(96, 20);
            this.label8.TabIndex = 45;
            this.label8.Text = "Mật Khẩu Cũ:";
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowAnimations = true;
            this.bunifuButton3.AllowMouseEffects = true;
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoRoundBorders = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "Thoát";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges1;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton3.ForeColor = System.Drawing.Color.Navy;
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.Navy;
            this.bunifuButton3.IdleBorderRadius = 1;
            this.bunifuButton3.IdleBorderThickness = 1;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(7, 350);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.OnDisabledState.BorderRadius = 1;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 1;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.BorderRadius = 1;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.Navy;
            this.bunifuButton3.OnIdleState.BorderRadius = 1;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.Navy;
            this.bunifuButton3.OnIdleState.IconLeftImage = null;
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 1;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(303, 31);
            this.bunifuButton3.TabIndex = 44;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            this.bunifuButton3.Click += new System.EventHandler(this.bunifuButton3_Click);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Cập Nhật Thông Tin Tài Khoản";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges2;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.Navy;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Navy;
            this.bunifuButton2.IdleBorderRadius = 1;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(7, 313);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.Navy;
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.Navy;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(303, 31);
            this.bunifuButton2.TabIndex = 43;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // btnCapNhatMatKhau
            // 
            this.btnCapNhatMatKhau.AllowAnimations = true;
            this.btnCapNhatMatKhau.AllowMouseEffects = true;
            this.btnCapNhatMatKhau.AllowToggling = false;
            this.btnCapNhatMatKhau.AnimationSpeed = 200;
            this.btnCapNhatMatKhau.AutoGenerateColors = false;
            this.btnCapNhatMatKhau.AutoRoundBorders = false;
            this.btnCapNhatMatKhau.AutoSizeLeftIcon = true;
            this.btnCapNhatMatKhau.AutoSizeRightIcon = true;
            this.btnCapNhatMatKhau.BackColor = System.Drawing.Color.Transparent;
            this.btnCapNhatMatKhau.BackColor1 = System.Drawing.Color.Transparent;
            this.btnCapNhatMatKhau.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCapNhatMatKhau.BackgroundImage")));
            this.btnCapNhatMatKhau.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCapNhatMatKhau.ButtonText = "Cập Nhật Mật Khẩu";
            this.btnCapNhatMatKhau.ButtonTextMarginLeft = 0;
            this.btnCapNhatMatKhau.ColorContrastOnClick = 45;
            this.btnCapNhatMatKhau.ColorContrastOnHover = 45;
            this.btnCapNhatMatKhau.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnCapNhatMatKhau.CustomizableEdges = borderEdges3;
            this.btnCapNhatMatKhau.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCapNhatMatKhau.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCapNhatMatKhau.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCapNhatMatKhau.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCapNhatMatKhau.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCapNhatMatKhau.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCapNhatMatKhau.ForeColor = System.Drawing.Color.Navy;
            this.btnCapNhatMatKhau.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCapNhatMatKhau.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCapNhatMatKhau.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCapNhatMatKhau.IconMarginLeft = 11;
            this.btnCapNhatMatKhau.IconPadding = 10;
            this.btnCapNhatMatKhau.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCapNhatMatKhau.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCapNhatMatKhau.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCapNhatMatKhau.IconSize = 25;
            this.btnCapNhatMatKhau.IdleBorderColor = System.Drawing.Color.Navy;
            this.btnCapNhatMatKhau.IdleBorderRadius = 1;
            this.btnCapNhatMatKhau.IdleBorderThickness = 1;
            this.btnCapNhatMatKhau.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnCapNhatMatKhau.IdleIconLeftImage = null;
            this.btnCapNhatMatKhau.IdleIconRightImage = null;
            this.btnCapNhatMatKhau.IndicateFocus = false;
            this.btnCapNhatMatKhau.Location = new System.Drawing.Point(7, 276);
            this.btnCapNhatMatKhau.Name = "btnCapNhatMatKhau";
            this.btnCapNhatMatKhau.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCapNhatMatKhau.OnDisabledState.BorderRadius = 1;
            this.btnCapNhatMatKhau.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCapNhatMatKhau.OnDisabledState.BorderThickness = 1;
            this.btnCapNhatMatKhau.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCapNhatMatKhau.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCapNhatMatKhau.OnDisabledState.IconLeftImage = null;
            this.btnCapNhatMatKhau.OnDisabledState.IconRightImage = null;
            this.btnCapNhatMatKhau.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCapNhatMatKhau.onHoverState.BorderRadius = 1;
            this.btnCapNhatMatKhau.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCapNhatMatKhau.onHoverState.BorderThickness = 1;
            this.btnCapNhatMatKhau.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCapNhatMatKhau.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCapNhatMatKhau.onHoverState.IconLeftImage = null;
            this.btnCapNhatMatKhau.onHoverState.IconRightImage = null;
            this.btnCapNhatMatKhau.OnIdleState.BorderColor = System.Drawing.Color.Navy;
            this.btnCapNhatMatKhau.OnIdleState.BorderRadius = 1;
            this.btnCapNhatMatKhau.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCapNhatMatKhau.OnIdleState.BorderThickness = 1;
            this.btnCapNhatMatKhau.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnCapNhatMatKhau.OnIdleState.ForeColor = System.Drawing.Color.Navy;
            this.btnCapNhatMatKhau.OnIdleState.IconLeftImage = null;
            this.btnCapNhatMatKhau.OnIdleState.IconRightImage = null;
            this.btnCapNhatMatKhau.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCapNhatMatKhau.OnPressedState.BorderRadius = 1;
            this.btnCapNhatMatKhau.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCapNhatMatKhau.OnPressedState.BorderThickness = 1;
            this.btnCapNhatMatKhau.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCapNhatMatKhau.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCapNhatMatKhau.OnPressedState.IconLeftImage = null;
            this.btnCapNhatMatKhau.OnPressedState.IconRightImage = null;
            this.btnCapNhatMatKhau.Size = new System.Drawing.Size(303, 31);
            this.btnCapNhatMatKhau.TabIndex = 42;
            this.btnCapNhatMatKhau.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCapNhatMatKhau.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCapNhatMatKhau.TextMarginLeft = 0;
            this.btnCapNhatMatKhau.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCapNhatMatKhau.UseDefaultRadiusAndThickness = true;
            this.btnCapNhatMatKhau.Click += new System.EventHandler(this.btnCapNhatMatKhau_Click);
            // 
            // txtNhapLaiMatKhau
            // 
            this.txtNhapLaiMatKhau.AcceptsReturn = false;
            this.txtNhapLaiMatKhau.AcceptsTab = false;
            this.txtNhapLaiMatKhau.AnimationSpeed = 200;
            this.txtNhapLaiMatKhau.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNhapLaiMatKhau.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNhapLaiMatKhau.BackColor = System.Drawing.Color.Transparent;
            this.txtNhapLaiMatKhau.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNhapLaiMatKhau.BackgroundImage")));
            this.txtNhapLaiMatKhau.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNhapLaiMatKhau.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNhapLaiMatKhau.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNhapLaiMatKhau.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNhapLaiMatKhau.BorderRadius = 1;
            this.txtNhapLaiMatKhau.BorderThickness = 1;
            this.txtNhapLaiMatKhau.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNhapLaiMatKhau.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNhapLaiMatKhau.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNhapLaiMatKhau.DefaultText = "";
            this.txtNhapLaiMatKhau.FillColor = System.Drawing.Color.White;
            this.txtNhapLaiMatKhau.HideSelection = true;
            this.txtNhapLaiMatKhau.IconLeft = null;
            this.txtNhapLaiMatKhau.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNhapLaiMatKhau.IconPadding = 10;
            this.txtNhapLaiMatKhau.IconRight = null;
            this.txtNhapLaiMatKhau.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNhapLaiMatKhau.Lines = new string[0];
            this.txtNhapLaiMatKhau.Location = new System.Drawing.Point(7, 237);
            this.txtNhapLaiMatKhau.MaxLength = 32767;
            this.txtNhapLaiMatKhau.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNhapLaiMatKhau.Modified = false;
            this.txtNhapLaiMatKhau.Multiline = false;
            this.txtNhapLaiMatKhau.Name = "txtNhapLaiMatKhau";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNhapLaiMatKhau.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNhapLaiMatKhau.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNhapLaiMatKhau.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNhapLaiMatKhau.OnIdleState = stateProperties24;
            this.txtNhapLaiMatKhau.Padding = new System.Windows.Forms.Padding(3);
            this.txtNhapLaiMatKhau.PasswordChar = '\0';
            this.txtNhapLaiMatKhau.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNhapLaiMatKhau.PlaceholderText = "Nhập Lại Mật Khẩu Mới";
            this.txtNhapLaiMatKhau.ReadOnly = false;
            this.txtNhapLaiMatKhau.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNhapLaiMatKhau.SelectedText = "";
            this.txtNhapLaiMatKhau.SelectionLength = 0;
            this.txtNhapLaiMatKhau.SelectionStart = 0;
            this.txtNhapLaiMatKhau.ShortcutsEnabled = true;
            this.txtNhapLaiMatKhau.Size = new System.Drawing.Size(303, 30);
            this.txtNhapLaiMatKhau.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNhapLaiMatKhau.TabIndex = 41;
            this.txtNhapLaiMatKhau.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNhapLaiMatKhau.TextMarginBottom = 0;
            this.txtNhapLaiMatKhau.TextMarginLeft = 3;
            this.txtNhapLaiMatKhau.TextMarginTop = 0;
            this.txtNhapLaiMatKhau.TextPlaceholder = "Nhập Lại Mật Khẩu Mới";
            this.txtNhapLaiMatKhau.UseSystemPasswordChar = false;
            this.txtNhapLaiMatKhau.WordWrap = true;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(3, 214);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(71, 20);
            this.label7.TabIndex = 40;
            this.label7.Text = "Nhập Lại:";
            // 
            // txtMatKhauMoi
            // 
            this.txtMatKhauMoi.AcceptsReturn = false;
            this.txtMatKhauMoi.AcceptsTab = false;
            this.txtMatKhauMoi.AnimationSpeed = 200;
            this.txtMatKhauMoi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMatKhauMoi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMatKhauMoi.BackColor = System.Drawing.Color.Transparent;
            this.txtMatKhauMoi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMatKhauMoi.BackgroundImage")));
            this.txtMatKhauMoi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMatKhauMoi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMatKhauMoi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMatKhauMoi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMatKhauMoi.BorderRadius = 1;
            this.txtMatKhauMoi.BorderThickness = 1;
            this.txtMatKhauMoi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMatKhauMoi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatKhauMoi.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtMatKhauMoi.DefaultText = "";
            this.txtMatKhauMoi.FillColor = System.Drawing.Color.White;
            this.txtMatKhauMoi.HideSelection = true;
            this.txtMatKhauMoi.IconLeft = null;
            this.txtMatKhauMoi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatKhauMoi.IconPadding = 10;
            this.txtMatKhauMoi.IconRight = null;
            this.txtMatKhauMoi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatKhauMoi.Lines = new string[0];
            this.txtMatKhauMoi.Location = new System.Drawing.Point(7, 181);
            this.txtMatKhauMoi.MaxLength = 32767;
            this.txtMatKhauMoi.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMatKhauMoi.Modified = false;
            this.txtMatKhauMoi.Multiline = false;
            this.txtMatKhauMoi.Name = "txtMatKhauMoi";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatKhauMoi.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMatKhauMoi.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatKhauMoi.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatKhauMoi.OnIdleState = stateProperties28;
            this.txtMatKhauMoi.Padding = new System.Windows.Forms.Padding(3);
            this.txtMatKhauMoi.PasswordChar = '\0';
            this.txtMatKhauMoi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMatKhauMoi.PlaceholderText = "Nhập Mật Khẩu Mới";
            this.txtMatKhauMoi.ReadOnly = false;
            this.txtMatKhauMoi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMatKhauMoi.SelectedText = "";
            this.txtMatKhauMoi.SelectionLength = 0;
            this.txtMatKhauMoi.SelectionStart = 0;
            this.txtMatKhauMoi.ShortcutsEnabled = true;
            this.txtMatKhauMoi.Size = new System.Drawing.Size(303, 30);
            this.txtMatKhauMoi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMatKhauMoi.TabIndex = 39;
            this.txtMatKhauMoi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMatKhauMoi.TextMarginBottom = 0;
            this.txtMatKhauMoi.TextMarginLeft = 3;
            this.txtMatKhauMoi.TextMarginTop = 0;
            this.txtMatKhauMoi.TextPlaceholder = "Nhập Mật Khẩu Mới";
            this.txtMatKhauMoi.UseSystemPasswordChar = false;
            this.txtMatKhauMoi.WordWrap = true;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(3, 158);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(105, 20);
            this.label3.TabIndex = 38;
            this.label3.Text = "Mật Khẩu Mới:";
            // 
            // txtDiaChi
            // 
            this.txtDiaChi.AcceptsReturn = false;
            this.txtDiaChi.AcceptsTab = false;
            this.txtDiaChi.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtDiaChi.AnimationSpeed = 200;
            this.txtDiaChi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDiaChi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDiaChi.BackColor = System.Drawing.Color.Transparent;
            this.txtDiaChi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDiaChi.BackgroundImage")));
            this.txtDiaChi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDiaChi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDiaChi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDiaChi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDiaChi.BorderRadius = 1;
            this.txtDiaChi.BorderThickness = 1;
            this.txtDiaChi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDiaChi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDiaChi.DefaultText = "";
            this.txtDiaChi.FillColor = System.Drawing.Color.White;
            this.txtDiaChi.HideSelection = true;
            this.txtDiaChi.IconLeft = null;
            this.txtDiaChi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.IconPadding = 10;
            this.txtDiaChi.IconRight = null;
            this.txtDiaChi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.Lines = new string[0];
            this.txtDiaChi.Location = new System.Drawing.Point(18, 450);
            this.txtDiaChi.MaxLength = 32767;
            this.txtDiaChi.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDiaChi.Modified = false;
            this.txtDiaChi.Multiline = false;
            this.txtDiaChi.Name = "txtDiaChi";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDiaChi.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnIdleState = stateProperties32;
            this.txtDiaChi.Padding = new System.Windows.Forms.Padding(3);
            this.txtDiaChi.PasswordChar = '\0';
            this.txtDiaChi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDiaChi.PlaceholderText = "Số nhà, Tên đường, ...";
            this.txtDiaChi.ReadOnly = false;
            this.txtDiaChi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDiaChi.SelectedText = "";
            this.txtDiaChi.SelectionLength = 0;
            this.txtDiaChi.SelectionStart = 0;
            this.txtDiaChi.ShortcutsEnabled = true;
            this.txtDiaChi.Size = new System.Drawing.Size(303, 30);
            this.txtDiaChi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDiaChi.TabIndex = 37;
            this.txtDiaChi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDiaChi.TextMarginBottom = 0;
            this.txtDiaChi.TextMarginLeft = 3;
            this.txtDiaChi.TextMarginTop = 0;
            this.txtDiaChi.TextPlaceholder = "Số nhà, Tên đường, ...";
            this.txtDiaChi.UseSystemPasswordChar = false;
            this.txtDiaChi.WordWrap = true;
            // 
            // cbXa
            // 
            this.cbXa.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.cbXa.BackColor = System.Drawing.Color.Transparent;
            this.cbXa.BackgroundColor = System.Drawing.Color.White;
            this.cbXa.BorderColor = System.Drawing.Color.Silver;
            this.cbXa.BorderRadius = 1;
            this.cbXa.Color = System.Drawing.Color.Silver;
            this.cbXa.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbXa.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbXa.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbXa.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbXa.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbXa.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbXa.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbXa.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbXa.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbXa.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbXa.FillDropDown = true;
            this.cbXa.FillIndicator = false;
            this.cbXa.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbXa.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.cbXa.ForeColor = System.Drawing.Color.Black;
            this.cbXa.FormattingEnabled = true;
            this.cbXa.Icon = null;
            this.cbXa.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbXa.IndicatorColor = System.Drawing.Color.Gray;
            this.cbXa.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbXa.ItemBackColor = System.Drawing.Color.White;
            this.cbXa.ItemBorderColor = System.Drawing.Color.White;
            this.cbXa.ItemForeColor = System.Drawing.Color.Black;
            this.cbXa.ItemHeight = 26;
            this.cbXa.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cbXa.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbXa.ItemTopMargin = 3;
            this.cbXa.Location = new System.Drawing.Point(18, 412);
            this.cbXa.Name = "cbXa";
            this.cbXa.Size = new System.Drawing.Size(303, 32);
            this.cbXa.TabIndex = 36;
            this.cbXa.Text = "Xã / Phường";
            this.cbXa.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbXa.TextLeftMargin = 5;
            // 
            // cbHuyen
            // 
            this.cbHuyen.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.cbHuyen.BackColor = System.Drawing.Color.Transparent;
            this.cbHuyen.BackgroundColor = System.Drawing.Color.White;
            this.cbHuyen.BorderColor = System.Drawing.Color.Silver;
            this.cbHuyen.BorderRadius = 1;
            this.cbHuyen.Color = System.Drawing.Color.Silver;
            this.cbHuyen.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbHuyen.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbHuyen.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbHuyen.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbHuyen.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbHuyen.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbHuyen.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbHuyen.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbHuyen.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbHuyen.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbHuyen.FillDropDown = true;
            this.cbHuyen.FillIndicator = false;
            this.cbHuyen.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbHuyen.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.cbHuyen.ForeColor = System.Drawing.Color.Black;
            this.cbHuyen.FormattingEnabled = true;
            this.cbHuyen.Icon = null;
            this.cbHuyen.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbHuyen.IndicatorColor = System.Drawing.Color.Gray;
            this.cbHuyen.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbHuyen.ItemBackColor = System.Drawing.Color.White;
            this.cbHuyen.ItemBorderColor = System.Drawing.Color.White;
            this.cbHuyen.ItemForeColor = System.Drawing.Color.Black;
            this.cbHuyen.ItemHeight = 26;
            this.cbHuyen.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cbHuyen.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbHuyen.ItemTopMargin = 3;
            this.cbHuyen.Location = new System.Drawing.Point(18, 374);
            this.cbHuyen.Name = "cbHuyen";
            this.cbHuyen.Size = new System.Drawing.Size(303, 32);
            this.cbHuyen.TabIndex = 35;
            this.cbHuyen.Text = "Quận / Huyện";
            this.cbHuyen.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbHuyen.TextLeftMargin = 5;
            this.cbHuyen.SelectedValueChanged += new System.EventHandler(this.cbHuyen_SelectedValueChanged);
            // 
            // cbTinh
            // 
            this.cbTinh.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.cbTinh.BackColor = System.Drawing.Color.Transparent;
            this.cbTinh.BackgroundColor = System.Drawing.Color.White;
            this.cbTinh.BorderColor = System.Drawing.Color.Silver;
            this.cbTinh.BorderRadius = 1;
            this.cbTinh.Color = System.Drawing.Color.Silver;
            this.cbTinh.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbTinh.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbTinh.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbTinh.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbTinh.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbTinh.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbTinh.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbTinh.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbTinh.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbTinh.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbTinh.FillDropDown = true;
            this.cbTinh.FillIndicator = false;
            this.cbTinh.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbTinh.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.cbTinh.ForeColor = System.Drawing.Color.Black;
            this.cbTinh.FormattingEnabled = true;
            this.cbTinh.Icon = null;
            this.cbTinh.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbTinh.IndicatorColor = System.Drawing.Color.Gray;
            this.cbTinh.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbTinh.ItemBackColor = System.Drawing.Color.White;
            this.cbTinh.ItemBorderColor = System.Drawing.Color.White;
            this.cbTinh.ItemForeColor = System.Drawing.Color.Black;
            this.cbTinh.ItemHeight = 26;
            this.cbTinh.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cbTinh.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbTinh.ItemTopMargin = 3;
            this.cbTinh.Location = new System.Drawing.Point(18, 336);
            this.cbTinh.Name = "cbTinh";
            this.cbTinh.Size = new System.Drawing.Size(303, 32);
            this.cbTinh.TabIndex = 34;
            this.cbTinh.Text = "Tỉnh / Thành Phố";
            this.cbTinh.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbTinh.TextLeftMargin = 5;
            this.cbTinh.SelectedValueChanged += new System.EventHandler(this.cbTinh_SelectedValueChanged);
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.bunifuLabel4.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel4.Location = new System.Drawing.Point(18, 310);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(49, 20);
            this.bunifuLabel4.TabIndex = 33;
            this.bunifuLabel4.Text = "Địa chỉ:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = true;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = this.panel1;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // FrmThongTinTK
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(670, 502);
            this.Controls.Add(this.txtDiaChi);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.cbXa);
            this.Controls.Add(this.txtEmail);
            this.Controls.Add(this.cbHuyen);
            this.Controls.Add(this.pnTTTaiKhoan);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.cbTinh);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.txtTenCuaHang);
            this.Controls.Add(this.txtSoDT);
            this.Controls.Add(this.txtHoTen);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FrmThongTinTK";
            this.Text = "FrmThongTinTK";
            this.Load += new System.EventHandler(this.FrmThongTinTK_Load);
            this.pnTTTaiKhoan.ResumeLayout(false);
            this.pnTTTaiKhoan.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txtSoDT;
        private Bunifu.UI.WinForms.BunifuTextBox txtHoTen;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox txtTenCuaHang;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private System.Windows.Forms.Panel pnTTTaiKhoan;
        private Bunifu.UI.WinForms.BunifuTextBox txtDiaChi;
        private Bunifu.UI.WinForms.BunifuDropdown cbXa;
        private Bunifu.UI.WinForms.BunifuDropdown cbHuyen;
        private Bunifu.UI.WinForms.BunifuDropdown cbTinh;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCapNhatMatKhau;
        private Bunifu.UI.WinForms.BunifuTextBox txtNhapLaiMatKhau;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox txtMatKhauMoi;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.UI.WinForms.BunifuTextBox txtMatKhauCu;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.PictureBox pictureBox1;
    }
}