namespace QuanLyDVGiaoHang.GUI.TaoDon
{
    partial class FrmTaoDonKH
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmTaoDonKH));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.txtTenNguoiGui = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtTenNguoiNhan = new Bunifu.UI.WinForms.BunifuTextBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.txtThongTinHangHoa = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtPhiCOD = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dtpNgayTaoDon = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.txtDiaChi2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cbXa2 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cbHuyen2 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cbTinh2 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.txtDiaChi1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cbXa1 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cbHuyen1 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cbTinh1 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // txtTenNguoiGui
            // 
            this.txtTenNguoiGui.AcceptsReturn = false;
            this.txtTenNguoiGui.AcceptsTab = false;
            this.txtTenNguoiGui.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtTenNguoiGui.AnimationSpeed = 200;
            this.txtTenNguoiGui.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTenNguoiGui.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTenNguoiGui.BackColor = System.Drawing.Color.Transparent;
            this.txtTenNguoiGui.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTenNguoiGui.BackgroundImage")));
            this.txtTenNguoiGui.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTenNguoiGui.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTenNguoiGui.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTenNguoiGui.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTenNguoiGui.BorderRadius = 1;
            this.txtTenNguoiGui.BorderThickness = 1;
            this.txtTenNguoiGui.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTenNguoiGui.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNguoiGui.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTenNguoiGui.DefaultText = "";
            this.txtTenNguoiGui.Enabled = false;
            this.txtTenNguoiGui.FillColor = System.Drawing.Color.White;
            this.txtTenNguoiGui.HideSelection = true;
            this.txtTenNguoiGui.IconLeft = null;
            this.txtTenNguoiGui.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNguoiGui.IconPadding = 10;
            this.txtTenNguoiGui.IconRight = null;
            this.txtTenNguoiGui.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNguoiGui.Lines = new string[0];
            this.txtTenNguoiGui.Location = new System.Drawing.Point(80, 32);
            this.txtTenNguoiGui.MaxLength = 32767;
            this.txtTenNguoiGui.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTenNguoiGui.Modified = false;
            this.txtTenNguoiGui.Multiline = false;
            this.txtTenNguoiGui.Name = "txtTenNguoiGui";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNguoiGui.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTenNguoiGui.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNguoiGui.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNguoiGui.OnIdleState = stateProperties4;
            this.txtTenNguoiGui.Padding = new System.Windows.Forms.Padding(3);
            this.txtTenNguoiGui.PasswordChar = '\0';
            this.txtTenNguoiGui.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTenNguoiGui.PlaceholderText = "Nhập Tên Người Gửi";
            this.txtTenNguoiGui.ReadOnly = false;
            this.txtTenNguoiGui.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTenNguoiGui.SelectedText = "";
            this.txtTenNguoiGui.SelectionLength = 0;
            this.txtTenNguoiGui.SelectionStart = 0;
            this.txtTenNguoiGui.ShortcutsEnabled = true;
            this.txtTenNguoiGui.Size = new System.Drawing.Size(232, 37);
            this.txtTenNguoiGui.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTenNguoiGui.TabIndex = 1;
            this.txtTenNguoiGui.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTenNguoiGui.TextMarginBottom = 0;
            this.txtTenNguoiGui.TextMarginLeft = 3;
            this.txtTenNguoiGui.TextMarginTop = 0;
            this.txtTenNguoiGui.TextPlaceholder = "Nhập Tên Người Gửi";
            this.txtTenNguoiGui.UseSystemPasswordChar = false;
            this.txtTenNguoiGui.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(6, 42);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(72, 20);
            this.bunifuLabel1.TabIndex = 3;
            this.bunifuLabel1.Text = "Người Gửi:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.Location = new System.Drawing.Point(327, 42);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(84, 20);
            this.bunifuLabel2.TabIndex = 4;
            this.bunifuLabel2.Text = "Người Nhận:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(6, 85);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(124, 20);
            this.bunifuLabel3.TabIndex = 5;
            this.bunifuLabel3.Text = "Địa Chỉ Người Gửi:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.Location = new System.Drawing.Point(327, 85);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(136, 20);
            this.bunifuLabel4.TabIndex = 6;
            this.bunifuLabel4.Text = "Địa Chỉ Người Nhận:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.Location = new System.Drawing.Point(6, 268);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(99, 20);
            this.bunifuLabel5.TabIndex = 7;
            this.bunifuLabel5.Text = "Ngày Tạo Đơn:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.Location = new System.Drawing.Point(327, 268);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(58, 20);
            this.bunifuLabel7.TabIndex = 9;
            this.bunifuLabel7.Text = "Phí COD:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtTenNguoiNhan
            // 
            this.txtTenNguoiNhan.AcceptsReturn = false;
            this.txtTenNguoiNhan.AcceptsTab = false;
            this.txtTenNguoiNhan.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.txtTenNguoiNhan.AnimationSpeed = 200;
            this.txtTenNguoiNhan.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTenNguoiNhan.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTenNguoiNhan.BackColor = System.Drawing.Color.Transparent;
            this.txtTenNguoiNhan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTenNguoiNhan.BackgroundImage")));
            this.txtTenNguoiNhan.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTenNguoiNhan.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTenNguoiNhan.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTenNguoiNhan.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTenNguoiNhan.BorderRadius = 1;
            this.txtTenNguoiNhan.BorderThickness = 1;
            this.txtTenNguoiNhan.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTenNguoiNhan.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNguoiNhan.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTenNguoiNhan.DefaultText = "";
            this.txtTenNguoiNhan.FillColor = System.Drawing.Color.White;
            this.txtTenNguoiNhan.HideSelection = true;
            this.txtTenNguoiNhan.IconLeft = null;
            this.txtTenNguoiNhan.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNguoiNhan.IconPadding = 10;
            this.txtTenNguoiNhan.IconRight = null;
            this.txtTenNguoiNhan.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNguoiNhan.Lines = new string[0];
            this.txtTenNguoiNhan.Location = new System.Drawing.Point(417, 32);
            this.txtTenNguoiNhan.MaxLength = 32767;
            this.txtTenNguoiNhan.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTenNguoiNhan.Modified = false;
            this.txtTenNguoiNhan.Multiline = false;
            this.txtTenNguoiNhan.Name = "txtTenNguoiNhan";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNguoiNhan.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTenNguoiNhan.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNguoiNhan.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNguoiNhan.OnIdleState = stateProperties8;
            this.txtTenNguoiNhan.Padding = new System.Windows.Forms.Padding(3);
            this.txtTenNguoiNhan.PasswordChar = '\0';
            this.txtTenNguoiNhan.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTenNguoiNhan.PlaceholderText = "Nhập Tên Người Nhận";
            this.txtTenNguoiNhan.ReadOnly = false;
            this.txtTenNguoiNhan.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTenNguoiNhan.SelectedText = "";
            this.txtTenNguoiNhan.SelectionLength = 0;
            this.txtTenNguoiNhan.SelectionStart = 0;
            this.txtTenNguoiNhan.ShortcutsEnabled = true;
            this.txtTenNguoiNhan.Size = new System.Drawing.Size(232, 37);
            this.txtTenNguoiNhan.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTenNguoiNhan.TabIndex = 10;
            this.txtTenNguoiNhan.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTenNguoiNhan.TextMarginBottom = 0;
            this.txtTenNguoiNhan.TextMarginLeft = 3;
            this.txtTenNguoiNhan.TextMarginTop = 0;
            this.txtTenNguoiNhan.TextPlaceholder = "Nhập Tên Người Nhận";
            this.txtTenNguoiNhan.UseSystemPasswordChar = false;
            this.txtTenNguoiNhan.WordWrap = true;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.Navy;
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(695, 40);
            this.panel1.TabIndex = 11;
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox2.Location = new System.Drawing.Point(136, 59);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(553, 10);
            this.groupBox2.TabIndex = 11;
            this.groupBox2.TabStop = false;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI Semibold", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.Navy;
            this.label1.Location = new System.Drawing.Point(12, 43);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(121, 37);
            this.label1.TabIndex = 10;
            this.label1.Text = "Tạo Đơn";
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox1.Controls.Add(this.txtThongTinHangHoa);
            this.groupBox1.Controls.Add(this.bunifuLabel6);
            this.groupBox1.Controls.Add(this.txtPhiCOD);
            this.groupBox1.Controls.Add(this.dtpNgayTaoDon);
            this.groupBox1.Controls.Add(this.txtDiaChi2);
            this.groupBox1.Controls.Add(this.cbXa2);
            this.groupBox1.Controls.Add(this.cbHuyen2);
            this.groupBox1.Controls.Add(this.cbTinh2);
            this.groupBox1.Controls.Add(this.txtDiaChi1);
            this.groupBox1.Controls.Add(this.cbXa1);
            this.groupBox1.Controls.Add(this.cbHuyen1);
            this.groupBox1.Controls.Add(this.cbTinh1);
            this.groupBox1.Controls.Add(this.txtTenNguoiGui);
            this.groupBox1.Controls.Add(this.bunifuLabel1);
            this.groupBox1.Controls.Add(this.bunifuLabel2);
            this.groupBox1.Controls.Add(this.txtTenNguoiNhan);
            this.groupBox1.Controls.Add(this.bunifuLabel7);
            this.groupBox1.Controls.Add(this.bunifuLabel3);
            this.groupBox1.Controls.Add(this.bunifuLabel5);
            this.groupBox1.Controls.Add(this.bunifuLabel4);
            this.groupBox1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.ForeColor = System.Drawing.Color.Navy;
            this.groupBox1.Location = new System.Drawing.Point(19, 89);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(663, 411);
            this.groupBox1.TabIndex = 12;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Thông Tin Đơn Hàng";
            // 
            // txtThongTinHangHoa
            // 
            this.txtThongTinHangHoa.AcceptsReturn = false;
            this.txtThongTinHangHoa.AcceptsTab = false;
            this.txtThongTinHangHoa.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.txtThongTinHangHoa.AnimationSpeed = 200;
            this.txtThongTinHangHoa.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtThongTinHangHoa.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtThongTinHangHoa.BackColor = System.Drawing.Color.Transparent;
            this.txtThongTinHangHoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtThongTinHangHoa.BackgroundImage")));
            this.txtThongTinHangHoa.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtThongTinHangHoa.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtThongTinHangHoa.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtThongTinHangHoa.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtThongTinHangHoa.BorderRadius = 1;
            this.txtThongTinHangHoa.BorderThickness = 1;
            this.txtThongTinHangHoa.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtThongTinHangHoa.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtThongTinHangHoa.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtThongTinHangHoa.DefaultText = "";
            this.txtThongTinHangHoa.FillColor = System.Drawing.Color.White;
            this.txtThongTinHangHoa.HideSelection = true;
            this.txtThongTinHangHoa.IconLeft = null;
            this.txtThongTinHangHoa.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtThongTinHangHoa.IconPadding = 10;
            this.txtThongTinHangHoa.IconRight = null;
            this.txtThongTinHangHoa.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtThongTinHangHoa.Lines = new string[0];
            this.txtThongTinHangHoa.Location = new System.Drawing.Point(80, 358);
            this.txtThongTinHangHoa.MaxLength = 32767;
            this.txtThongTinHangHoa.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtThongTinHangHoa.Modified = false;
            this.txtThongTinHangHoa.Multiline = false;
            this.txtThongTinHangHoa.Name = "txtThongTinHangHoa";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtThongTinHangHoa.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtThongTinHangHoa.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtThongTinHangHoa.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtThongTinHangHoa.OnIdleState = stateProperties12;
            this.txtThongTinHangHoa.Padding = new System.Windows.Forms.Padding(3);
            this.txtThongTinHangHoa.PasswordChar = '\0';
            this.txtThongTinHangHoa.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtThongTinHangHoa.PlaceholderText = "Nhập Thông Tin Hàng Hóa";
            this.txtThongTinHangHoa.ReadOnly = false;
            this.txtThongTinHangHoa.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtThongTinHangHoa.SelectedText = "";
            this.txtThongTinHangHoa.SelectionLength = 0;
            this.txtThongTinHangHoa.SelectionStart = 0;
            this.txtThongTinHangHoa.ShortcutsEnabled = true;
            this.txtThongTinHangHoa.Size = new System.Drawing.Size(569, 37);
            this.txtThongTinHangHoa.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtThongTinHangHoa.TabIndex = 31;
            this.txtThongTinHangHoa.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtThongTinHangHoa.TextMarginBottom = 0;
            this.txtThongTinHangHoa.TextMarginLeft = 3;
            this.txtThongTinHangHoa.TextMarginTop = 0;
            this.txtThongTinHangHoa.TextPlaceholder = "Nhập Thông Tin Hàng Hóa";
            this.txtThongTinHangHoa.UseSystemPasswordChar = false;
            this.txtThongTinHangHoa.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(6, 332);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(141, 20);
            this.bunifuLabel6.TabIndex = 30;
            this.bunifuLabel6.Text = "Thông Tin Hàng Hóa:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtPhiCOD
            // 
            this.txtPhiCOD.AcceptsReturn = false;
            this.txtPhiCOD.AcceptsTab = false;
            this.txtPhiCOD.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.txtPhiCOD.AnimationSpeed = 200;
            this.txtPhiCOD.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPhiCOD.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPhiCOD.BackColor = System.Drawing.Color.Transparent;
            this.txtPhiCOD.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPhiCOD.BackgroundImage")));
            this.txtPhiCOD.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPhiCOD.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPhiCOD.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPhiCOD.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPhiCOD.BorderRadius = 1;
            this.txtPhiCOD.BorderThickness = 1;
            this.txtPhiCOD.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPhiCOD.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhiCOD.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPhiCOD.DefaultText = "";
            this.txtPhiCOD.FillColor = System.Drawing.Color.White;
            this.txtPhiCOD.HideSelection = true;
            this.txtPhiCOD.IconLeft = null;
            this.txtPhiCOD.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhiCOD.IconPadding = 10;
            this.txtPhiCOD.IconRight = null;
            this.txtPhiCOD.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhiCOD.Lines = new string[0];
            this.txtPhiCOD.Location = new System.Drawing.Point(417, 289);
            this.txtPhiCOD.MaxLength = 32767;
            this.txtPhiCOD.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPhiCOD.Modified = false;
            this.txtPhiCOD.Multiline = false;
            this.txtPhiCOD.Name = "txtPhiCOD";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhiCOD.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPhiCOD.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhiCOD.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhiCOD.OnIdleState = stateProperties16;
            this.txtPhiCOD.Padding = new System.Windows.Forms.Padding(3);
            this.txtPhiCOD.PasswordChar = '\0';
            this.txtPhiCOD.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPhiCOD.PlaceholderText = "Nhập Tiền Cần Thu";
            this.txtPhiCOD.ReadOnly = false;
            this.txtPhiCOD.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPhiCOD.SelectedText = "";
            this.txtPhiCOD.SelectionLength = 0;
            this.txtPhiCOD.SelectionStart = 0;
            this.txtPhiCOD.ShortcutsEnabled = true;
            this.txtPhiCOD.Size = new System.Drawing.Size(232, 37);
            this.txtPhiCOD.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPhiCOD.TabIndex = 29;
            this.txtPhiCOD.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPhiCOD.TextMarginBottom = 0;
            this.txtPhiCOD.TextMarginLeft = 3;
            this.txtPhiCOD.TextMarginTop = 0;
            this.txtPhiCOD.TextPlaceholder = "Nhập Tiền Cần Thu";
            this.txtPhiCOD.UseSystemPasswordChar = false;
            this.txtPhiCOD.WordWrap = true;
            // 
            // dtpNgayTaoDon
            // 
            this.dtpNgayTaoDon.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dtpNgayTaoDon.BackColor = System.Drawing.Color.Transparent;
            this.dtpNgayTaoDon.BorderRadius = 1;
            this.dtpNgayTaoDon.Color = System.Drawing.Color.Silver;
            this.dtpNgayTaoDon.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtpNgayTaoDon.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtpNgayTaoDon.DisabledColor = System.Drawing.Color.Gray;
            this.dtpNgayTaoDon.DisplayWeekNumbers = false;
            this.dtpNgayTaoDon.DPHeight = 0;
            this.dtpNgayTaoDon.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtpNgayTaoDon.Enabled = false;
            this.dtpNgayTaoDon.FillDatePicker = false;
            this.dtpNgayTaoDon.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtpNgayTaoDon.ForeColor = System.Drawing.Color.Black;
            this.dtpNgayTaoDon.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpNgayTaoDon.Icon = ((System.Drawing.Image)(resources.GetObject("dtpNgayTaoDon.Icon")));
            this.dtpNgayTaoDon.IconColor = System.Drawing.Color.Gray;
            this.dtpNgayTaoDon.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtpNgayTaoDon.LeftTextMargin = 5;
            this.dtpNgayTaoDon.Location = new System.Drawing.Point(80, 294);
            this.dtpNgayTaoDon.MinimumSize = new System.Drawing.Size(4, 32);
            this.dtpNgayTaoDon.Name = "dtpNgayTaoDon";
            this.dtpNgayTaoDon.Size = new System.Drawing.Size(232, 32);
            this.dtpNgayTaoDon.TabIndex = 28;
            // 
            // txtDiaChi2
            // 
            this.txtDiaChi2.AcceptsReturn = false;
            this.txtDiaChi2.AcceptsTab = false;
            this.txtDiaChi2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.txtDiaChi2.AnimationSpeed = 200;
            this.txtDiaChi2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDiaChi2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDiaChi2.BackColor = System.Drawing.Color.Transparent;
            this.txtDiaChi2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDiaChi2.BackgroundImage")));
            this.txtDiaChi2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDiaChi2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDiaChi2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDiaChi2.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDiaChi2.BorderRadius = 1;
            this.txtDiaChi2.BorderThickness = 1;
            this.txtDiaChi2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDiaChi2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi2.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDiaChi2.DefaultText = "";
            this.txtDiaChi2.FillColor = System.Drawing.Color.White;
            this.txtDiaChi2.HideSelection = true;
            this.txtDiaChi2.IconLeft = null;
            this.txtDiaChi2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi2.IconPadding = 10;
            this.txtDiaChi2.IconRight = null;
            this.txtDiaChi2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi2.Lines = new string[0];
            this.txtDiaChi2.Location = new System.Drawing.Point(417, 225);
            this.txtDiaChi2.MaxLength = 32767;
            this.txtDiaChi2.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDiaChi2.Modified = false;
            this.txtDiaChi2.Multiline = false;
            this.txtDiaChi2.Name = "txtDiaChi2";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi2.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDiaChi2.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi2.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi2.OnIdleState = stateProperties20;
            this.txtDiaChi2.Padding = new System.Windows.Forms.Padding(3);
            this.txtDiaChi2.PasswordChar = '\0';
            this.txtDiaChi2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDiaChi2.PlaceholderText = "Số nhà, Tên đường, ...";
            this.txtDiaChi2.ReadOnly = false;
            this.txtDiaChi2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDiaChi2.SelectedText = "";
            this.txtDiaChi2.SelectionLength = 0;
            this.txtDiaChi2.SelectionStart = 0;
            this.txtDiaChi2.ShortcutsEnabled = true;
            this.txtDiaChi2.Size = new System.Drawing.Size(232, 37);
            this.txtDiaChi2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDiaChi2.TabIndex = 27;
            this.txtDiaChi2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDiaChi2.TextMarginBottom = 0;
            this.txtDiaChi2.TextMarginLeft = 3;
            this.txtDiaChi2.TextMarginTop = 0;
            this.txtDiaChi2.TextPlaceholder = "Số nhà, Tên đường, ...";
            this.txtDiaChi2.UseSystemPasswordChar = false;
            this.txtDiaChi2.WordWrap = true;
            // 
            // cbXa2
            // 
            this.cbXa2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.cbXa2.BackColor = System.Drawing.Color.Transparent;
            this.cbXa2.BackgroundColor = System.Drawing.Color.White;
            this.cbXa2.BorderColor = System.Drawing.Color.Silver;
            this.cbXa2.BorderRadius = 1;
            this.cbXa2.Color = System.Drawing.Color.Silver;
            this.cbXa2.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbXa2.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbXa2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbXa2.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbXa2.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbXa2.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbXa2.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbXa2.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbXa2.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbXa2.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbXa2.FillDropDown = true;
            this.cbXa2.FillIndicator = false;
            this.cbXa2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbXa2.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.cbXa2.ForeColor = System.Drawing.Color.Black;
            this.cbXa2.FormattingEnabled = true;
            this.cbXa2.Icon = null;
            this.cbXa2.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbXa2.IndicatorColor = System.Drawing.Color.Gray;
            this.cbXa2.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbXa2.ItemBackColor = System.Drawing.Color.White;
            this.cbXa2.ItemBorderColor = System.Drawing.Color.White;
            this.cbXa2.ItemForeColor = System.Drawing.Color.Black;
            this.cbXa2.ItemHeight = 26;
            this.cbXa2.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cbXa2.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbXa2.ItemTopMargin = 3;
            this.cbXa2.Location = new System.Drawing.Point(417, 187);
            this.cbXa2.Name = "cbXa2";
            this.cbXa2.Size = new System.Drawing.Size(232, 32);
            this.cbXa2.TabIndex = 26;
            this.cbXa2.Text = "Xã / Phường";
            this.cbXa2.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbXa2.TextLeftMargin = 5;
            // 
            // cbHuyen2
            // 
            this.cbHuyen2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.cbHuyen2.BackColor = System.Drawing.Color.Transparent;
            this.cbHuyen2.BackgroundColor = System.Drawing.Color.White;
            this.cbHuyen2.BorderColor = System.Drawing.Color.Silver;
            this.cbHuyen2.BorderRadius = 1;
            this.cbHuyen2.Color = System.Drawing.Color.Silver;
            this.cbHuyen2.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbHuyen2.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbHuyen2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbHuyen2.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbHuyen2.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbHuyen2.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbHuyen2.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbHuyen2.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbHuyen2.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbHuyen2.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbHuyen2.FillDropDown = true;
            this.cbHuyen2.FillIndicator = false;
            this.cbHuyen2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbHuyen2.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.cbHuyen2.ForeColor = System.Drawing.Color.Black;
            this.cbHuyen2.FormattingEnabled = true;
            this.cbHuyen2.Icon = null;
            this.cbHuyen2.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbHuyen2.IndicatorColor = System.Drawing.Color.Gray;
            this.cbHuyen2.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbHuyen2.ItemBackColor = System.Drawing.Color.White;
            this.cbHuyen2.ItemBorderColor = System.Drawing.Color.White;
            this.cbHuyen2.ItemForeColor = System.Drawing.Color.Black;
            this.cbHuyen2.ItemHeight = 26;
            this.cbHuyen2.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cbHuyen2.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbHuyen2.ItemTopMargin = 3;
            this.cbHuyen2.Location = new System.Drawing.Point(417, 149);
            this.cbHuyen2.Name = "cbHuyen2";
            this.cbHuyen2.Size = new System.Drawing.Size(232, 32);
            this.cbHuyen2.TabIndex = 25;
            this.cbHuyen2.Text = "Quận / Huyện";
            this.cbHuyen2.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbHuyen2.TextLeftMargin = 5;
            this.cbHuyen2.SelectedValueChanged += new System.EventHandler(this.cbHuyen2_SelectedValueChanged);
            // 
            // cbTinh2
            // 
            this.cbTinh2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.cbTinh2.BackColor = System.Drawing.Color.Transparent;
            this.cbTinh2.BackgroundColor = System.Drawing.Color.White;
            this.cbTinh2.BorderColor = System.Drawing.Color.Silver;
            this.cbTinh2.BorderRadius = 1;
            this.cbTinh2.Color = System.Drawing.Color.Silver;
            this.cbTinh2.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbTinh2.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbTinh2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbTinh2.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbTinh2.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbTinh2.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbTinh2.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbTinh2.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbTinh2.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbTinh2.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbTinh2.FillDropDown = true;
            this.cbTinh2.FillIndicator = false;
            this.cbTinh2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbTinh2.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.cbTinh2.ForeColor = System.Drawing.Color.Black;
            this.cbTinh2.FormattingEnabled = true;
            this.cbTinh2.Icon = null;
            this.cbTinh2.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbTinh2.IndicatorColor = System.Drawing.Color.Gray;
            this.cbTinh2.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbTinh2.ItemBackColor = System.Drawing.Color.White;
            this.cbTinh2.ItemBorderColor = System.Drawing.Color.White;
            this.cbTinh2.ItemForeColor = System.Drawing.Color.Black;
            this.cbTinh2.ItemHeight = 26;
            this.cbTinh2.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cbTinh2.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbTinh2.ItemTopMargin = 3;
            this.cbTinh2.Location = new System.Drawing.Point(417, 111);
            this.cbTinh2.Name = "cbTinh2";
            this.cbTinh2.Size = new System.Drawing.Size(232, 32);
            this.cbTinh2.TabIndex = 24;
            this.cbTinh2.Text = "Tỉnh / Thành Phố";
            this.cbTinh2.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbTinh2.TextLeftMargin = 5;
            this.cbTinh2.SelectedValueChanged += new System.EventHandler(this.cbTinh2_SelectedValueChanged);
            // 
            // txtDiaChi1
            // 
            this.txtDiaChi1.AcceptsReturn = false;
            this.txtDiaChi1.AcceptsTab = false;
            this.txtDiaChi1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtDiaChi1.AnimationSpeed = 200;
            this.txtDiaChi1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDiaChi1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDiaChi1.BackColor = System.Drawing.Color.Transparent;
            this.txtDiaChi1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDiaChi1.BackgroundImage")));
            this.txtDiaChi1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDiaChi1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDiaChi1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDiaChi1.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDiaChi1.BorderRadius = 1;
            this.txtDiaChi1.BorderThickness = 1;
            this.txtDiaChi1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDiaChi1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDiaChi1.DefaultText = "";
            this.txtDiaChi1.FillColor = System.Drawing.Color.White;
            this.txtDiaChi1.HideSelection = true;
            this.txtDiaChi1.IconLeft = null;
            this.txtDiaChi1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi1.IconPadding = 10;
            this.txtDiaChi1.IconRight = null;
            this.txtDiaChi1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi1.Lines = new string[0];
            this.txtDiaChi1.Location = new System.Drawing.Point(80, 225);
            this.txtDiaChi1.MaxLength = 32767;
            this.txtDiaChi1.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDiaChi1.Modified = false;
            this.txtDiaChi1.Multiline = false;
            this.txtDiaChi1.Name = "txtDiaChi1";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi1.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDiaChi1.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi1.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi1.OnIdleState = stateProperties24;
            this.txtDiaChi1.Padding = new System.Windows.Forms.Padding(3);
            this.txtDiaChi1.PasswordChar = '\0';
            this.txtDiaChi1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDiaChi1.PlaceholderText = "Số nhà, Tên đường, ...";
            this.txtDiaChi1.ReadOnly = false;
            this.txtDiaChi1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDiaChi1.SelectedText = "";
            this.txtDiaChi1.SelectionLength = 0;
            this.txtDiaChi1.SelectionStart = 0;
            this.txtDiaChi1.ShortcutsEnabled = true;
            this.txtDiaChi1.Size = new System.Drawing.Size(232, 37);
            this.txtDiaChi1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDiaChi1.TabIndex = 23;
            this.txtDiaChi1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDiaChi1.TextMarginBottom = 0;
            this.txtDiaChi1.TextMarginLeft = 3;
            this.txtDiaChi1.TextMarginTop = 0;
            this.txtDiaChi1.TextPlaceholder = "Số nhà, Tên đường, ...";
            this.txtDiaChi1.UseSystemPasswordChar = false;
            this.txtDiaChi1.WordWrap = true;
            // 
            // cbXa1
            // 
            this.cbXa1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.cbXa1.BackColor = System.Drawing.Color.Transparent;
            this.cbXa1.BackgroundColor = System.Drawing.Color.White;
            this.cbXa1.BorderColor = System.Drawing.Color.Silver;
            this.cbXa1.BorderRadius = 1;
            this.cbXa1.Color = System.Drawing.Color.Silver;
            this.cbXa1.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbXa1.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbXa1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbXa1.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbXa1.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbXa1.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbXa1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbXa1.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbXa1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbXa1.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbXa1.FillDropDown = true;
            this.cbXa1.FillIndicator = false;
            this.cbXa1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbXa1.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.cbXa1.ForeColor = System.Drawing.Color.Black;
            this.cbXa1.FormattingEnabled = true;
            this.cbXa1.Icon = null;
            this.cbXa1.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbXa1.IndicatorColor = System.Drawing.Color.Gray;
            this.cbXa1.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbXa1.ItemBackColor = System.Drawing.Color.White;
            this.cbXa1.ItemBorderColor = System.Drawing.Color.White;
            this.cbXa1.ItemForeColor = System.Drawing.Color.Black;
            this.cbXa1.ItemHeight = 26;
            this.cbXa1.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cbXa1.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbXa1.ItemTopMargin = 3;
            this.cbXa1.Location = new System.Drawing.Point(80, 187);
            this.cbXa1.Name = "cbXa1";
            this.cbXa1.Size = new System.Drawing.Size(232, 32);
            this.cbXa1.TabIndex = 22;
            this.cbXa1.Text = "Xã / Phường";
            this.cbXa1.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbXa1.TextLeftMargin = 5;
            // 
            // cbHuyen1
            // 
            this.cbHuyen1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.cbHuyen1.BackColor = System.Drawing.Color.Transparent;
            this.cbHuyen1.BackgroundColor = System.Drawing.Color.White;
            this.cbHuyen1.BorderColor = System.Drawing.Color.Silver;
            this.cbHuyen1.BorderRadius = 1;
            this.cbHuyen1.Color = System.Drawing.Color.Silver;
            this.cbHuyen1.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbHuyen1.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbHuyen1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbHuyen1.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbHuyen1.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbHuyen1.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbHuyen1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbHuyen1.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbHuyen1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbHuyen1.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbHuyen1.FillDropDown = true;
            this.cbHuyen1.FillIndicator = false;
            this.cbHuyen1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbHuyen1.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.cbHuyen1.ForeColor = System.Drawing.Color.Black;
            this.cbHuyen1.FormattingEnabled = true;
            this.cbHuyen1.Icon = null;
            this.cbHuyen1.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbHuyen1.IndicatorColor = System.Drawing.Color.Gray;
            this.cbHuyen1.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbHuyen1.ItemBackColor = System.Drawing.Color.White;
            this.cbHuyen1.ItemBorderColor = System.Drawing.Color.White;
            this.cbHuyen1.ItemForeColor = System.Drawing.Color.Black;
            this.cbHuyen1.ItemHeight = 26;
            this.cbHuyen1.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cbHuyen1.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbHuyen1.ItemTopMargin = 3;
            this.cbHuyen1.Location = new System.Drawing.Point(80, 149);
            this.cbHuyen1.Name = "cbHuyen1";
            this.cbHuyen1.Size = new System.Drawing.Size(232, 32);
            this.cbHuyen1.TabIndex = 21;
            this.cbHuyen1.Text = "Quận / Huyện";
            this.cbHuyen1.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbHuyen1.TextLeftMargin = 5;
            this.cbHuyen1.SelectedValueChanged += new System.EventHandler(this.cbHuyen1_SelectedValueChanged);
            // 
            // cbTinh1
            // 
            this.cbTinh1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.cbTinh1.BackColor = System.Drawing.Color.Transparent;
            this.cbTinh1.BackgroundColor = System.Drawing.Color.White;
            this.cbTinh1.BorderColor = System.Drawing.Color.Silver;
            this.cbTinh1.BorderRadius = 1;
            this.cbTinh1.Color = System.Drawing.Color.Silver;
            this.cbTinh1.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbTinh1.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbTinh1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbTinh1.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbTinh1.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbTinh1.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbTinh1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbTinh1.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbTinh1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbTinh1.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbTinh1.FillDropDown = true;
            this.cbTinh1.FillIndicator = false;
            this.cbTinh1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbTinh1.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.cbTinh1.ForeColor = System.Drawing.Color.Black;
            this.cbTinh1.FormattingEnabled = true;
            this.cbTinh1.Icon = null;
            this.cbTinh1.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbTinh1.IndicatorColor = System.Drawing.Color.Gray;
            this.cbTinh1.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbTinh1.ItemBackColor = System.Drawing.Color.White;
            this.cbTinh1.ItemBorderColor = System.Drawing.Color.White;
            this.cbTinh1.ItemForeColor = System.Drawing.Color.Black;
            this.cbTinh1.ItemHeight = 26;
            this.cbTinh1.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cbTinh1.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbTinh1.ItemTopMargin = 3;
            this.cbTinh1.Location = new System.Drawing.Point(80, 111);
            this.cbTinh1.Name = "cbTinh1";
            this.cbTinh1.Size = new System.Drawing.Size(232, 32);
            this.cbTinh1.TabIndex = 20;
            this.cbTinh1.Text = "Tỉnh / Thành Phố";
            this.cbTinh1.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbTinh1.TextLeftMargin = 5;
            this.cbTinh1.SelectedValueChanged += new System.EventHandler(this.cbTinh1_SelectedValueChanged);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Thoát";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges1;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.Navy;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Navy;
            this.bunifuButton2.IdleBorderRadius = 1;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(534, 506);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.Navy;
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.Navy;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(134, 39);
            this.bunifuButton2.TabIndex = 31;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Tạo Đơn";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges2;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.Navy;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Navy;
            this.bunifuButton1.IdleBorderRadius = 1;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(382, 506);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.Navy;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.Navy;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(137, 39);
            this.bunifuButton1.TabIndex = 30;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = true;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = this.panel1;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // FrmTaoDonKH
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(695, 555);
            this.Controls.Add(this.bunifuButton2);
            this.Controls.Add(this.bunifuButton1);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.label1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FrmTaoDonKH";
            this.Text = "TaoDonKH";
            this.Load += new System.EventHandler(this.TaoDonKH_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuTextBox txtTenNguoiGui;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox txtTenNguoiNhan;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.GroupBox groupBox1;
        private Bunifu.UI.WinForms.BunifuTextBox txtDiaChi2;
        private Bunifu.UI.WinForms.BunifuDropdown cbXa2;
        private Bunifu.UI.WinForms.BunifuDropdown cbHuyen2;
        private Bunifu.UI.WinForms.BunifuDropdown cbTinh2;
        private Bunifu.UI.WinForms.BunifuTextBox txtDiaChi1;
        private Bunifu.UI.WinForms.BunifuDropdown cbXa1;
        private Bunifu.UI.WinForms.BunifuDropdown cbHuyen1;
        private Bunifu.UI.WinForms.BunifuDropdown cbTinh1;
        private Bunifu.UI.WinForms.BunifuTextBox txtPhiCOD;
        private Bunifu.UI.WinForms.BunifuDatePicker dtpNgayTaoDon;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.UI.WinForms.BunifuTextBox txtThongTinHangHoa;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
    }
}